version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka_container
    image: debezium/kafka:1.1
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - "zookeeper"

  kafdrop:
    container_name: kafdrop_container
    image: obsidiandynamics/kafdrop:3.24.0
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - 9000:9000
    depends_on:
      - kafka